[package]
name = "timetable-optimizer-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
timetable-optimizer-lib = { path = "../lib" }
cached = "0.47.0"
calamine = "0.24.0"
chrono = { version = "0.4.31", features = ["serde"] }
imageproc = "0.24.0"
indicatif = "0.17.7"
itertools = "0.12.0"
permutator = "0.4.3"
rayon = "1.8.1"
ab_glyph = "0.2.24"
rustyline = "13.0.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
