[package]
name = "timetable-optimizer-web"
version = "0.1.0"
edition = "2021"

[dependencies]
timetable-optimizer-lib = { path = "../lib" }
calamine = "0.24.0"
gloo = "0.11.0"
js-sys = "0.3.69"
web-sys = "0.3.69"
yew = { version="0.20", features=["csr"] }
